### ISSUE TITLE
Looking for a little insight into @BeforeAll

### ISSUE THREAD

**Issue by DGilmour5** [camunda-community-hub/camunda-bpm-junit5#8]
I'm attempting to follow best practices of only one assert per test method. So to save time, I want the class instantiated only once instead of what jUnit does (instantiate a new class for every method). I'm trying this, but getting an error that the process definition is not deployed.
Thoughts?
```
@TestInstance(Lifecycle.PER_CLASS)
@ExtendWith(ProcessEngineExtension.class)
class FirstTryTestCase {

	private ProcessInstance processInstance;
	
	@BeforeAll
	@Deployment(resources = {"Process1.bpmn"})
	void startUp() {
		processInstance = runtimeService().startProcessInstanceByKey("Process1", Variables.putValue("variable1", false));
	}
	
	@Test
	void deploymentActiveTest() {
		
		assertThat(processInstance).isActive();
	}

}
```

**Comment by ingorichtsmeier** [comment]
Hi @DGilmour5,

if you want a single deployment, you can add the annotation `@Deployment` to the class, as tested here: https://github.com/camunda-community-hub/camunda-bpm-junit5/blob/master/core/src/test/java/org/camunda/bpm/extension/junit5/ProcessEngineExtensionResourcesDeploymentTest.java

Otherwise the extension will only check test methods for a deployment annotation. I think, that in your example the annotation is just ignored.

Hope this helps, Ingo
